# swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs

# Configurações gerais do Actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    instances:
      solicitacao:
        minimum-number-of-calls: 1
        sliding-window-size: 1